<a href="https://colab.research.google.com/github/Hoang-Quang-Thang/Thang/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Các phép toán trong numpy

In [47]:
import numpy as np

In [23]:
x = np.array([[2, 4, 6],
              [1, 3, 5]])
y = np.array([[3, 5, 7],
              [4, 6, 8]])
z = np.array([[3, 5, 7],
              [4, 6, 8],
              [1, 3, 5]])


In [20]:
a = np.add(x,y)   # tổng
b = np.subtract(x,y)  # hiệu
c = np.multiply(x,y)  # tích
d = np.divide(x,y)    # thương
e = np.transpose(x)   # chuyển vị 1 ma trận
f = x = np.invert(x)  # đảo nghịch ma trận
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

[[0 0 0]
 [2 2 2]]
[[ -6 -10 -14]
 [ -6 -10 -14]]
[[ -9 -25 -49]
 [ -8 -24 -48]]
[[-1.         -1.         -1.        ]
 [-0.5        -0.66666667 -0.75      ]]
[[-3 -2]
 [-5 -4]
 [-7 -6]]
[[2 4 6]
 [1 3 5]]


In [ ]:
Các kiểu kiến tạo mảng

In [7]:
a = np.zeros((2,2))   # Tạo một numpy array 2 hàng 2 cột với tất cả phẩn tử là 0
print(a)             

b = np.ones((1,2))    # Tạo một numpy array 1 hàng 2 cột với tất cả phẩn tử là 1
print(b)              

c = np.full((2,3), 7)  # Tạo một mảng hằng 2 hàng 3 cột với giá trị là 7
print(c)              

d = np.eye(2)         # Tạo một ma trận đơn vị 2 x 2
print(d)             

e = np.random.random((2,3))  # Tạo một mảng với 2 hàng và 3 cột
print(e) 

f = np.arange(10) # Tạo 1 numpy array với các phẩn tử từ 0 đến 9
print(f)          

g = np.arange(0)  # Tạo 1 numpy array rỗng
print(g)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7 7]
 [7 7 7]]
[[1. 0.]
 [0. 1.]]
[[0.11581679 0.82588204 0.69203066]
 [0.46461796 0.41608525 0.22545229]]
[0 1 2 3 4 5 6 7 8 9]
[]


In [ ]:
Thao tác với mảng 

In [8]:
print("Kiểu dữ liệu của phần tử trong mảng:", x.dtype)
print("Kích thước của mảng:", x.shape)
print("Số phần tử trong mảng:", x.size)
print("Số chiều của mảng:", x.ndim)

Kiểu dữ liệu của phần tử trong mảng: int64
Kích thước của mảng: (2, 3)
Số phần tử trong mảng: 6
Số chiều của mảng: 2


In [ ]:
Truy xuất phần tử trong mảng    # hàng và cột luôn bắt đầu với hàng [0] và cột [0]

In [45]:
print("x[2]=", x[1])           # truy cập các phần tử ở hàng 2 của mẳng 
print("x[2:3]=", x[1,2])       # phần tử ở hàng 2 cột 3 của mảng 
print("x[:,:1]=", x[:,:2])     # Truy cập tới phần tử từ cột 0 đến cột 1 của tất cả các hàng 
print([x for x in zip(*z)])    # phân tích ra các ma trận bên trong 

x[2]= [1 3 5]
x[2:3]= 5
x[:,:1]= [[2 4]
 [1 3]]
[(3, 4, 1), (5, 6, 3), (7, 8, 5)]


In [ ]:
Các hàm thống kê

In [53]:
print("Giá trị lớn nhất của mảng là:", np.max(x))
print("Giá trị nhỏ nhất của mảng là:", np.min(x))
print("Tổng tất cả các phần tử của mảng là:", np.sum(x))
print("Trung bình cộng tất cả các phần tử của mảng là:", np.mean(x))
print("Giá trị trung vị của mảng là:", np.median(x))

Giá trị lớn nhất của mảng là: 6
Giá trị nhỏ nhất của mảng là: 1
Tổng tất cả các phần tử của mảng là: 21
Trung bình cộng tất cả các phần tử của mảng là: 3.5
Giá trị trung vị của mảng là: 3.5
