<a href="https://colab.research.google.com/github/Hoang-Quang-Thang/Thang/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np

In [17]:
x = np.array([[2, 4, 6],
              [4, 6, 8]])
y = np.array([[1, 3, 5],
              [3, 5, 7]])

In [19]:
a = np.add(x,y)   # tong 
b = np.subtract(x,y)  # hieu
c = np.multiply(x,y)  # tich
d = np.divide(x,y)    # thuong
e = np.transpose(y)   # chuyen vi 1 ma tran
print(a)
print(b)
print(c)
print(d)
print(e)

[[ 3  7 11]
 [ 7 11 15]]
[[1 1 1]
 [1 1 1]]
[[ 2 12 30]
 [12 30 56]]
[[2.         1.33333333 1.2       ]
 [1.33333333 1.2        1.14285714]]
[[1 3]
 [3 5]
 [5 7]]
